config/routes.rb
Rails.application.routes.draw do

  resources :administrators


  get '/rooms', to: 'rooms#index'
  resources :reservations, shallow: true do
    resources :rooms
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'

  namespace :admin do
    resources :reservations
    resources :profiles
  end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many_attached :images
    has_and_belongs_to_many :reservations
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @test = Reservation.where("check_out >= ? AND check_in <= ? ", params[:fecha], params[:fecha_final])
    @rooms = Room.all
    @temp = [] 
    @test.each do |reservation|
      reservation.rooms.each do |d|
        @temp << d
      end
    end
    @available = (@rooms-@temp).uniq
  end

  def show
  end

  def create
      reservations_rooms_params 
      gets
      last_reservation = User.find(1).reservations.last
      n = last_reservation.reservations_rooms.new reservations_rooms_params 
      n.save!
  end

  def destroy
  end

  def update
  end

  def new
  end


  private 

  def reservations_rooms_params 
    params.require(:reservations_room)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/create.html.haml
%h1 Rooms#create
%p Find me in app/views/rooms/create.html.haml

app/views/rooms/destroy.html.haml
%h1 Rooms#destroy
%p Find me in app/views/rooms/destroy.html.haml

app/views/rooms/index.html.haml
%h1 Rooms#index
%p Find me in app/views/rooms/index.html.haml
.container
  .row
    .col-6
      .row
        -# - @test = []
        -@available.each_with_index do |room,i|
          .col-12
            .name{id:"room#{i}"}
              =room.name
          .col-12
            .precio{id:"precio#{i}"}
              =room.base_price
              -# -@test << room.id
            %input{id:"#{i}", type: "checkbox"}
    .col-6
      .card
        .card-title
          busqueda
          =form_tag rooms_path, method: :get do
            .field
              = date_field_tag :fecha, class: "form-control"
            .field
              = date_field_tag :fecha_final, class: "form-control"
            .field
              = submit_tag :search
      .card
        .card-title
          .col#check_in_field
            %span
              fecha entrada
            %span
              200
          .col#check_out_field
            %span
              fecha salida
            %span
              200
          =form_tag new_reservation_path, method: :get do
            .field
              = date_field_tag :fecha, Date.today
            .field
              = date_field_tag :fecha_final,  Date.today
            .field
              = hidden_field_tag :aval, @test

      .card
        .card-title
          .col
            #list
              = hidden_field_tag :room, @test
              = hidden_field_tag :roomTwo, @test
              = hidden_field_tag :roomTree, @test
              = hidden_field_tag :roomFour, @test
      .card
        .card-title
          .col
            total
            %input{id: "total", type:"text", name:"total", size:"3"}
            = hidden_field_tag 'total', @test
          .col
            = submit_tag :continuar

app/views/rooms/new.html.haml
%h1 Rooms#new
%p Find me in app/views/rooms/new.html.haml

app/views/rooms/show.html.haml
%h1 Reservations#new
%p cuartos a reservar
.container#reservations
.container
  .row
    .col-7
      .row
        -# - @test = []
        -@available.each_with_index do |room,i|
          .col.d-none{id:"id#{i}"}
            =room.id
          .col-12
            .row
              .col-3.titleRoom
                .name{id:"room#{i}"}
                  =room.name
              .col-9.subtitleRoom
                %p Lorem, ipsum dolor.
            .row
              .col.subtitleRoom2
                %p Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, ea!
            .row
              .col.bg-contenido
                .name
                  = image_tag 'carousel1'
                  -# =image_tag url_for(room.images.first)
            .row.bg-contenido2.justify-content-between
              .col-2.l
                servicio 1
              .col-2.lv
                servicio 1
              .col-2.lv
                servicio 1
              .col-2.lv
                .precio{id:"precio#{i}"}
                  =room.base_price
                  -# -@test << room.id
              .col-2
                %input{id:"#{i}", type: "checkbox"}
    .col-3
      .card
        .card-body
          .titleRoom.ml-3.mt-2
            reserva
          =form_tag rooms_path, method: :get do
            .col
              .field.subtitleDate.mt-3.mr-2
                fecha de entrada
                = date_field_tag :fecha, class: "form-control"
              .field.subtitleDate
                fecha de salida
                = date_field_tag :fecha_final, class: "form-control"
              .field
                = submit_tag :consulta, class: 'btnSearch'
      .card
        .card-title.titleRoom.mb-4
          Recibo de reserva
        .card-title
          = form_for @reservation do |f|
            .field.subtitleDate
              =f.label "fecha de entrada"
            .field.subtitleDate
              =f.date_field :check_in, value: params[:fecha]
            .field.subtitleDate
              =f.label "fecha de salida"
            .field
              =f.date_field :check_out , value: params[:fecha_final]
              =f.hidden_field :stimated_cost, id: "stimated"
            = f.fields_for :reservations_rooms do |neste|
              .field
                = neste.hidden_field :room_id, id: "tokyo2"
            = f.fields_for :reservations_rooms do |neste|
              .field
                = neste.hidden_field :room_id, id: "deluxe2"
            = f.fields_for :reservations_rooms do |neste|
              .field
                = neste.hidden_field :room_id, id: "viena2"
            = f.fields_for :reservations_rooms do |neste|
              .field
                = neste.hidden_field :room_id, id: "caracas2"
                = hidden_field_tag :aval, @test
            .card
              .card-body
                .row.p-0
                  .col-12.p-0
                    #list.subtitleDate
                      %strong
                        Habitaciones:
            .card
              .card-body
                .row
                  .col-12.p-0
                    #taxes
                      %strong
                        Impuestos:
            .card
              .card-body
                .field.subtitleDate
                  %strong
                    total
                  %input{id: "total", type:"text", name:"total", size:"3"}
              = f.submit

app/views/rooms/update.html.haml
%h1 Rooms#update
%p Find me in app/views/rooms/update.html.haml